server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: provider1
    prefer-ip-address: true
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/youlexuandb?useUnicode=true&characterEncoding=UTF-8
mybatis:
  #配置扫描xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.offcn.pojo
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql